#!/usr/bin/env bash
# Usage ./1-world_wide_web <domain> <subdomain>

# Function to retrieve and display information about a subdomain
domain_information () {
    # Perform a DNS lookup on the subdomain
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    # Display the subdomain, record type, and IP address
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

# If there is one argument, call the function for each subdomain
if [ "$#" == 1 ]
then
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
# If there are two arguments, call the function for the specified subdomain
elif [ "$#" == 2 ]
then
  domain_information "$1" "$2"
fi
