#!/usr/bin/env bash
# Configure my Nginx server to have a custom 404 page

# Update package list & Installing Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Allowing write permissions to the HTML file & Add content to the HTML file
sudo chmod 666 /var/www/html/index.html
sudo echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo mkdir -p /var/www/mohamedezzat.tech/html

# Create a custom 404 HTML page
sudo echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/mohamedezzat.tech/html/custom_404.html > /dev/null

# Configure Nginx:
# - Add a rewrite rule for redirecting /redirect_me to a LinkedIn profile
# - Set up a custom 404 error page pointing to the created HTML file
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\tlocation \/redirect_me {\n\t\treturn 301 https://www.linkedin.com/in/mohamed-ezzat01/;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\tinternal;\n\t\troot /var/www/mohamedezzat.tech/html;\n\t}' /etc/nginx/sites-available/default

# Starting the Nginx service
sudo service nginx start
sudo nginx -s reload
