#!/usr/bin/env bash

# Update package list & Installing Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Create a custom 404 HTML page
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configure Nginx:
# - Add a rewrite rule for redirecting /redirect_me to a LinkedIn profile
# - Set up a custom 404 error page pointing to the created HTML file
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.linkedin.com\/in\/mohamed-ezzat01 permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default

# Starting the Nginx service
sudo service nginx start
