#!/usr/bin/env bash
# configures Nginx so that its HTTP response contains a custom header on web-01 and web-02

# Update the package list and Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Allow Nginx HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a basic index.html file and a custom 404.html page
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo sh -c 'echo "Ceci n'\''est pas une page" > /var/www/html/404.html'

# add the custom header line inside the server block in the Nginx configuration
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Check the Nginx configuration syntax & Restart the Nginx service to apply the changes
sudo nginx -t
sudo service nginx restart
