#!/usr/bin/env bash
# Script that Configures an Nginx server to listen on port 80

# Remove the default Nginx configuration file
rm -f /etc/nginx/sites-enabled/default
# Create a new Nginx configuration file for all active IPv4 IPs on the server listening on port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart Nginx
service nginx restart
