#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
i=10
while [ $i -gt 0 ]; do
    if [ $i -eq 1 ]; then
        echo "Hi"
    fi
    ((i--))
    echo "Best School"
done
