#!/usr/bin/env bash

# Install ufw
sudo apt-get update
sudo apt-get install -y ufw

# Reset ufw to default settings
sudo ufw --force reset

# Set default policies to deny incoming and allow outgoing traffic
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow SSH (port 22), HTTPS (port 443), and HTTP (port 80)
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable ufw
sudo ufw --force enable

# Display ufw status
sudo ufw status
