#!/usr/bin/env bash
# configures Nginx to run as the nginx user

# Create a system user named 'nginx' without a home directory, with /bin/false as the login shell, and disable interactive login.
sudo adduser --system --no-create-home --shell /bin/false --group --disabled-login nginx

# Terminate any running processes with the name 'apache2'.
pkill -f apache2

# Set the file permission of /etc/nginx/nginx.conf to 644 making it readable and writable by the owner (root) and readable by others.
chmod 644 /etc/nginx/nginx.conf

# Add 'user nginx;' at the beginning of the /etc/nginx/nginx.conf file.
sed -i "1i user nginx;" /etc/nginx/nginx.conf

# Replace '80' with '8080' in the /etc/nginx/sites-enabled/default file.
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default

# Restart the Nginx service as the 'nginx' user.
sudo -u nginx service nginx restart
