#!/usr/bin/env bash
# as task 1 but short and sweet.
sudo adduser --system --no-create-home --shell /bin/false --group --disabled-login nginx
pkill -f apache2
sed -i '1i user nginx;' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
